
 
PRAGMA foreign_keys = OFF;

drop table if exists ACCOUNTS;
drop table if exists ACTIVITY;
drop table if exists CAUSEOFLOSS;
drop table if exists COUNTRY;
drop table if exists FOODCLASS;
drop table if exists FOODGROUP;
drop table if exists FOODSUBCLASS;
drop table if exists FOODSUPPLY;
drop table if exists LOCATIO;
drop table if exists LOSSSTATS;
drop table if exists STUDENTCODE;
drop table if exists TAKESPARTIN;


PRAGMA foreign_keys = ON;
/*  Data Definition */

CREATE TABLE ACTIVITY
        (ACTIVITY      VARCHAR,

        PRIMARY KEY (ACTIVITY)
        )
        WITHOUT ROWID;

CREATE TABLE CAUSEOFLOSS
        (CAUSEOFLOSS      VARCHAR,

        PRIMARY KEY (CAUSEOFLOSS)
        )
        WITHOUT ROWID;

CREATE TABLE FOODSUPPLY
        (FOODSUPPLY      VARCHAR,

        PRIMARY KEY (FOODSUPPLY)
        )
        WITHOUT ROWID;





CREATE TABLE COUNTRY
        (M49CODE      VARCHAR,
        COUNTRY       VARCHAR UNIQUE NOT NULL, 

        PRIMARY KEY (M49CODE)
        )
        WITHOUT ROWID;

CREATE TABLE LOCATIO
        (REGION       VARCHAR UNIQUE,
        M49CODE       VARCHAR NOT NULL,
        COUNTRY       VARCHAR NOT NULL, 

        PRIMARY KEY (REGION, M49CODE),

        FOREIGN KEY (M49CODE) REFERENCES COUNTRY(M49CODE) ,
        FOREIGN KEY (COUNTRY) REFERENCES COUNTRY(COUNTRY) 
        )
        WITHOUT ROWID;





CREATE TABLE FOODGROUP
        (GROUPCODE           VARCHAR,
        GROUPDESCRIPTOR      VARCHAR NOT NULL, 

        PRIMARY KEY (GROUPCODE)
        )
        WITHOUT ROWID;

CREATE TABLE FOODCLASS
        (CLASSCODE       VARCHAR,
        GROUPCODE        VARCHAR,
        CLASSDESCRIPTOR  VARCHAR NOT NULL,

        PRIMARY KEY (CLASSCODE, GROUPCODE), /* */

        FOREIGN KEY (GROUPCODE) REFERENCES FOODGROUP(GROUPCODE) 
        )
        WITHOUT ROWID;

CREATE TABLE FOODSUBCLASS
        (SUBCLASSCODE   VARCHAR,
        CLASSCODE       VARCHAR, 
        GROUPCODE        VARCHAR, 
        DESCRIPTOR  VARCHAR NOT NULL,

        PRIMARY KEY (SUBCLASSCODE, CLASSCODE, GROUPCODE),       /* */

        FOREIGN KEY (GROUPCODE) REFERENCES FOODGROUP(GROUPCODE),
        FOREIGN KEY (CLASSCODE) REFERENCES FOODCLASS(CLASSCODE) 
        )
        WITHOUT ROWID;

CREATE TABLE LOSSSTATS
        (ROW_ID          INTEGER,
        
        LOSSPERCENTAGE   FLOAT NOT NULL,
        YEAR             INTEGER NOT NULL,

        GROUPCODE        VARCHAR NOT NULL,     
        CLASSCODE        VARCHAR NOT NULL,      
        SUBCLASSCODE     VARCHAR,              
        DESCRIPTOR       VARCHAR NOT NULL,
        CAUSEOFLOSS      VARCHAR,
        M49CODE          VARCHAR NOT NULL,
        COUNTRY          VARCHAR NOT NULL,
        REGION           VARCHAR,
        

        PRIMARY KEY (ROW_ID),

        FOREIGN KEY (GROUPCODE) REFERENCES FOODGROUP(GROUPCODE),
        FOREIGN KEY (CLASSCODE) REFERENCES FOODCLASS(CLASSCODE),
        FOREIGN KEY (SUBCLASSCODE) REFERENCES FOODSUBCLASS(SUBCLASSCODE),
        FOREIGN KEY (DESCRIPTOR) REFERENCES FOODSUBCLASS(DESCRIPTOR),
        FOREIGN KEY (CAUSEOFLOSS) REFERENCES CAUSEOFLOSS(CAUSEOFLOSS),
        FOREIGN KEY (M49CODE) REFERENCES COUNTRY(M49CODE),
        FOREIGN KEY (COUNTRY) REFERENCES COUNTRY(COUNTRY),
        FOREIGN KEY (REGION) REFERENCES LOCATIO(REGION)

        )
        WITHOUT ROWID;





CREATE TABLE STUDENTCODE
        (STUDENTCODE      INTEGER,

        PRIMARY KEY (STUDENTCODE)
        )
        WITHOUT ROWID;

CREATE TABLE ACCOUNTS
        (USERNAME      VARCHAR,
        USERCODE       INTEGER UNIQUE NOT NULL,
        PASSCODE       VARCHAR UNIQUE,
        DESCRIPTOR     VARCHAR,
        STUDENTCODE    INTEGER,
        IMGLINKPATH    VARCHAR,   /* */

        PRIMARY KEY (USERCODE), /* */

        FOREIGN KEY (STUDENTCODE) REFERENCES STUDENTCODE(STUDENTCODE)
        )
        WITHOUT ROWID;





CREATE TABLE TAKESPARTIN
        (STATSROWID    INTEGER NOT NULL,
        ACTIVITY       VARCHAR NOT NULL,

        PRIMARY KEY (STATSROWID, ACTIVITY),

        FOREIGN KEY (STATSROWID) REFERENCES LOSSSTATS(ROW_ID),
        FOREIGN KEY (ACTIVITY) REFERENCES ACTIVITY(ACTIVITY)
        )
        WITHOUT ROWID;


